language: ruby
rvm:
  - 1.9.3
  - ruby-head

bundler_args: "--without development production assets"

matrix:
  allow_failures:
    - rvm: ruby-head

before_script:
  - "cp config/database.yml.sample config/database.yml"
  - "cp config/initializers/secret_token.rb.sample config/initializers/secret_token.rb"
script:
  - "bundle exec rake ci:tests"
