language: ruby
rvm:
  - 1.9.3
  - ruby-head

bundler_args: "--without development production assets"

matrix:
  allow_failures:
    - rvm: ruby-head

before_script:
  - "cp config/database.sample.yml config/database.yml"
script:
  - "bundle exec rake ci:tests"
